.TH "strdup.c" 3 "4 Dec 2008" "Version 1.6.4" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strdup.c \- 
.SH "Detailed Description"
.PP 

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBstrdup\fP (const char *s1)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for avr-libc from the source code.
