update=20.09.2015 22:51:53
last_client=kicad
[general]
version=1
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=
UseCmpFile=1
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[eeschema]
version=1
LibDir=acs712.pretty;C:/Users/Uwe/Downloads/ardumower/pcb/megashield_svn_1.3_geoeffnet/acs712.pretty;../../../../../../KiCad/share/modules
[eeschema/libraries]
LibName1=ardumower mega shield svn-cache
LibName2=acs712.pretty/Wlan_ESP8266
LibName3=power
LibName4=conn
LibName5=uln-udn
LibName6=C:/Users/Uwe/Documents/KICAD/BibliothekenUwe.pretty/power
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
