.TH "ldiv_t" 3 "4 Dec 2008" "Version 1.6.4" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ldiv_t \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Result type for function \fBldiv()\fP. 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBquot\fP"
.br
.ti -1c
.RI "long \fBrem\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long \fBldiv_t::quot\fP"
.PP
The Quotient. 
.SS "long \fBldiv_t::rem\fP"
.PP
The Remainder. 

.SH "Author"
.PP 
Generated automatically by Doxygen for avr-libc from the source code.
